In [3]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
arr2d=np.array([[1,2,3,4],[1,2,3,4]])
arr2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [10]:
print(arr[0]+arr[3])

5


In [12]:
print(arr2d[0,1],arr2d[0,-1])

2 4


In [13]:
print(arr[0:2]) #start & end

[1 2]


In [14]:
print(arr[0:4:2]) #start,end,step

[1 3]


In [17]:
print(arr.dtype)

int32


In [18]:
n_arr=arr.astype(bool)
n_arr

array([ True,  True,  True,  True,  True])

In [19]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
n_ar=ar.reshape(4,3)
n_ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
ar1d=arr2d.reshape(-1)
ar1d

array([1, 2, 3, 4, 1, 2, 3, 4])

In [22]:
print(n_ar.shape)

(4, 3)


In [23]:
x=np.where(arr%2==0)
print(x)

(array([1, 3], dtype=int64),)


In [24]:
arangee=np.arange(0,20,2)
print(arangee)

[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
np.random.randint(10,50,size=5)

array([31, 33, 36, 44, 32])

In [26]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(a+b)

[2 4 6]


# Pandas 

    # It is used to treat 1D, 2D etc type of array in order to analyze data

In [28]:
import pandas as pd
import os

In [31]:
path=os.getcwd()

In [35]:
df = pd.read_csv(path+'\\netflix_titles_nov_2019.csv')
df.shape

(5837, 12)

In [36]:
df.columns

Index(['show_id', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'type'],
      dtype='object')

In [37]:
df.tail()

show_id                        title              director  \
5832  70141644  Mad Ron's Prevues from Hell            Jim Monaco   
5833  70127998                     Splatter             Joe Dante   
5834  70084180      Just Another Love Story          Ole Bornedal   
5835  70157452              Dinner for Five                   NaN   
5836  70053412         To and From New York  Sorin Dan Mihalcescu   

                                                   cast        country  \
5832  Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...  United States   
5833  Corey Feldman, Tony Todd, Tara Leigh, Erin Way...  United States   
5834  Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...        Denmark   
5835                                                NaN  United States   
5836  Barbara King, Shaana Diya, John Krisiukenas, Y...  United States   

             date_added  release_year rating  duration  \
5832   November 1, 2010          1987     NR    84 min   
5833  November 18, 2009          2009  TV-14    29 min   
5834        May 5, 2009          2007     NR   104 min   
5835   February 4, 2008          2007  TV-MA  1 Season   
5836    January 1, 2008          2006     NR    81 min   

                                  listed_in  \
5832             Cult Movies, Horror Movies   
5833                          Horror Movies   
5834           Dramas, International Movies   
5835           Stand-Up Comedy & Talk Shows   
5836  Dramas, Independent Movies, Thrillers   

                                            description     type  
5832  This collection cherry-picks trailers, forgott...    Movie  
5833  After committing suicide, a washed-up rocker r...    Movie  
5834  When he causes a car accident that leaves a yo...    Movie  
5835  In each episode, four celebrities join host Jo...  TV Show  
5836  While covering a story in New York City, a Sea...    Movie

In [41]:
df['title'][10:50]

10                                          Payday
11                            Sugar Rush Christmas
12                              The Accidental Spy
13                            The Charming Stepmom
14                                      The Island
15                         The Movies That Made Us
16                                    Holiday Rush
17                                          Levius
18                                 Lugar de Mulher
19                            Merry Happy Whatever
20                                     Mythomaniac
21                                       The Score
22                                          Broken
23                                        Defiance
24                             Evvarikee Cheppoddu
25                        Little Singham: Mahabali
26    The Body Remembers When the World Broke Open
27                                    The Irishman
28                     Mike Birbiglia: The New One
29                   Super Mons

In [42]:
df[['title','type']]

title     type
0                               Chocolate  TV Show
1     Guatemala: Heart of the Mayan World    Movie
2                         The Zoya Factor    Movie
3                               Atlantics    Movie
4                         Chip and Potato  TV Show
...                                   ...      ...
5832          Mad Ron's Prevues from Hell    Movie
5833                             Splatter    Movie
5834              Just Another Love Story    Movie
5835                      Dinner for Five  TV Show
5836                 To and From New York    Movie

[5837 rows x 2 columns]

In [43]:
df[['title','type','country']]

title     type                   country
0                               Chocolate  TV Show               South Korea
1     Guatemala: Heart of the Mayan World    Movie                       NaN
2                         The Zoya Factor    Movie                     India
3                               Atlantics    Movie  France, Senegal, Belgium
4                         Chip and Potato  TV Show    Canada, United Kingdom
...                                   ...      ...                       ...
5832          Mad Ron's Prevues from Hell    Movie             United States
5833                             Splatter    Movie             United States
5834              Just Another Love Story    Movie                   Denmark
5835                      Dinner for Five  TV Show             United States
5836                 To and From New York    Movie             United States

[5837 rows x 3 columns]

In [48]:
df.iloc[2:5,1:5]

title         director  \
2  The Zoya Factor  Abhishek Sharma   
3        Atlantics        Mati Diop   
4  Chip and Potato              NaN   

                                                cast                   country  
2  Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...                     India  
3  Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...  France, Senegal, Belgium  
4  Abigail Oliver, Andrea Libman, Briana Buckmast...    Canada, United Kingdom

In [49]:
df[df['title']=='Chocolate']

show_id      title director  \
0  81193313  Chocolate      NaN   

                                                cast      country  \
0  Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...  South Korea   

          date_added  release_year rating  duration  \
0  November 30, 2019          2019  TV-14  1 Season   

                                           listed_in  \
0  International TV Shows, Korean TV Shows, Roman...   

                                         description     type  
0  Brought together by meaningful meals in the pa...  TV Show

In [50]:
df['type'].value_counts()

Movie      3939
TV Show    1898
Name: type, dtype: int64

In [55]:
df.isnull().sum()

show_id            0
title              0
director        1901
cast             556
country            0
date_added       642
release_year       0
rating            10
duration           0
listed_in          0
description        0
type               0
dtype: int64

In [52]:
df.dtypes

show_id          int64
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
type            object
dtype: object

In [53]:
df['date_added']=pd.to_datetime(df['date_added'])

In [54]:
df['country'].fillna('earth',inplace=True)

In [56]:
df.groupby('type',as_index=False).mean()

type       show_id  release_year
0    Movie  7.647438e+07   2012.836507
1  TV Show  7.901586e+07   2015.456797

In [57]:
df.describe()

show_id  release_year
count  5.837000e+03   5837.000000
mean   7.730079e+07   2013.688539
std    9.479777e+06      8.419088
min    2.698800e+05   1925.000000
25%    8.004520e+07   2013.000000
50%    8.016353e+07   2016.000000
75%    8.024188e+07   2018.000000
max    8.122720e+07   2020.000000